// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: product.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Images        string                 `protobuf:"bytes,3,opt,name=images,proto3" json:"images,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAddReq) Reset() {
	*x = ProductAddReq{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAddReq) ProtoMessage() {}

func (x *ProductAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAddReq.ProtoReflect.Descriptor instead.
func (*ProductAddReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAddReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductAddReq) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *ProductAddReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductAddReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type ProductAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAddResp) Reset() {
	*x = ProductAddResp{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAddResp) ProtoMessage() {}

func (x *ProductAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAddResp.ProtoReflect.Descriptor instead.
func (*ProductAddResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductAddResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ProductAddResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type OrderItemAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PayType       int64                  `protobuf:"varint,2,opt,name=payType,proto3" json:"payType,omitempty"`
	AddressId     int64                  `protobuf:"varint,3,opt,name=addressId,proto3" json:"addressId,omitempty"`
	List          []*OrderItem           `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemAddReq) Reset() {
	*x = OrderItemAddReq{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemAddReq) ProtoMessage() {}

func (x *OrderItemAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemAddReq.ProtoReflect.Descriptor instead.
func (*OrderItemAddReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemAddReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderItemAddReq) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderItemAddReq) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *OrderItemAddReq) GetList() []*OrderItem {
	if x != nil {
		return x.List
	}
	return nil
}

type OrderItemAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	PayUrl        string                 `protobuf:"bytes,2,opt,name=payUrl,proto3" json:"payUrl,omitempty"`
	Total         float32                `protobuf:"fixed32,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemAddResp) Reset() {
	*x = OrderItemAddResp{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemAddResp) ProtoMessage() {}

func (x *OrderItemAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemAddResp.ProtoReflect.Descriptor instead.
func (*OrderItemAddResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItemAddResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *OrderItemAddResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *OrderItemAddResp) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\x05proto\"\x93\x01\n" +
	"\rProductAddReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x16\n" +
	"\x06images\x18\x03 \x01(\tR\x06images\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x05 \x01(\x03R\n" +
	"categoryId\"6\n" +
	"\x0eProductAddResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"\x87\x01\n" +
	"\x0fOrderItemAddReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\apayType\x18\x02 \x01(\x03R\apayType\x12\x1c\n" +
	"\taddressId\x18\x03 \x01(\x03R\taddressId\x12$\n" +
	"\x04list\x18\x04 \x03(\v2\x10.proto.OrderItemR\x04list\"Z\n" +
	"\x10OrderItemAddResp\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06payUrl\x18\x02 \x01(\tR\x06payUrl\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x02R\x05total\"E\n" +
	"\tOrderItem\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity2\x85\x01\n" +
	"\aProduct\x129\n" +
	"\n" +
	"ProductAdd\x12\x14.proto.ProductAddReq\x1a\x15.proto.ProductAddResp\x12?\n" +
	"\fOrderItemAdd\x12\x16.proto.OrderItemAddReq\x1a\x17.proto.OrderItemAddRespB\x04Z\x02./b\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_proto_goTypes = []any{
	(*ProductAddReq)(nil),    // 0: proto.ProductAddReq
	(*ProductAddResp)(nil),   // 1: proto.ProductAddResp
	(*OrderItemAddReq)(nil),  // 2: proto.OrderItemAddReq
	(*OrderItemAddResp)(nil), // 3: proto.OrderItemAddResp
	(*OrderItem)(nil),        // 4: proto.OrderItem
}
var file_product_proto_depIdxs = []int32{
	4, // 0: proto.OrderItemAddReq.list:type_name -> proto.OrderItem
	0, // 1: proto.Product.ProductAdd:input_type -> proto.ProductAddReq
	2, // 2: proto.Product.OrderItemAdd:input_type -> proto.OrderItemAddReq
	1, // 3: proto.Product.ProductAdd:output_type -> proto.ProductAddResp
	3, // 4: proto.Product.OrderItemAdd:output_type -> proto.OrderItemAddResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
